[application]

name = "anki-cards"
# asset_dir = "assets"
default_platform = "desktop"

[web.app]
title = "project_name"
[web.watcher]
reload_html = true
watch_path = ["src"]
[web.resource]
style = [".\\styles.css"]
script = []

[web.resource.dev]
style = [".\\styles.css"]
script = []